apiVersion: v1
kind: Service
metadata:
  name: available-schedules-go
  labels: { app: available-schedules-go }
spec:
  selector: { app: available-schedules-go }
  ports:
    - name: http
      port: 80
      targetPort: 8080

