apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev.local
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: orders-api
                port: { number: 80 }
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: orders-api
                port: { number: 80 }
          - path: /api/v2
            pathType: Prefix
            backend:
              service:
                name: orders-api
                port: { number: 80 }
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: orders-api
                port: { number: 80 }