name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          #cache: "pip"
          cache-dependency-path: apps/available-schedules-python/requirements.txt

      - name: Install Python dependencies
        working-directory: apps/available-schedules-python
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Trivy security scan (Python)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'apps/available-schedules-python'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy security scan (Go)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'apps/available-schedules-go'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Run Python unit tests
        working-directory: apps/available-schedules-python
        run: |
          pytest -q tests \
                 --junitxml=report.xml \
                 --cov=. --cov-report=term-missing

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Go service
        working-directory: apps/available-schedules-go
        run: go build ./...
      
      - name: Run Go unit tests
        working-directory: apps/available-schedules-go
        run: go test -v ./...

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Verify frontend dependencies
        working-directory: apps/available-schedules-web
        run: npm install --omit=dev

      - name: Upload test report (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: apps/available-schedules-python/report.xml
